table 'Measure Table'
	lineageTag: f8cc1aca-46a6-45e9-8d45-417f01ea77c5

	measure 'Total Enrollments' = COUNT('Customer Loyalty History'[Loyalty Number])
		formatString: 0
		lineageTag: 32df1fca-f5c2-4624-ba4f-7aa84f1b9ce7

	measure 'Total Cancellations' = COUNT('Customer Loyalty History'[Cancellation Yr-Mth])
		formatString: 0
		lineageTag: 0f36b7da-4ee3-4fea-96e0-601367e75288

	measure 'Total Flights' =
			CALCULATE(
			    SUM('Customer Flight Activity'[Total Flights]),
			    USERELATIONSHIP('Calendar'[Yr-Mth],'Customer Flight Activity'[Flight Yr-Mth])
			    )
		formatString: 0
		lineageTag: be55e3c5-dde1-4a9e-bdb5-d50387f08f72

	measure 'Cancellation Rate' = DIVIDE([Total Cancellations],[Total Enrollments])
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 004cb091-6d92-47a1-a0e4-cb4469ae0073

	measure 'Previous Month Enrollments' =
			
			CALCULATE(
			    [Total Enrollments],
			    DATEADD(
			        'Calendar'[Yr-Mth],
			        -1,
			        MONTH
			    )
			)
		formatString: 0
		lineageTag: 1b896c65-dda7-47cf-a263-4b4f328b03d3

	measure 'Previous Month Cancellations' =
			
			CALCULATE(
			    [Total Cancellations],
			    DATEADD(
			        'Calendar'[Yr-Mth],
			        -1,
			        MONTH
			    )
			)
		formatString: 0
		lineageTag: fecf8161-63b8-4ce1-829c-71ded897a588

	measure 'Previous Month Flights' =
			
			CALCULATE(
			    [Total Flights],
			    DATEADD(
			        'Calendar'[Yr-Mth],
			        -1,
			        MONTH
			    )
			)
		formatString: 0
		lineageTag: e7c2e9fc-18fe-436d-a9ae-9279bac7397f

	measure 'Total Customers' = COUNT('Customer Loyalty History'[Loyalty Number])
		formatString: 0
		lineageTag: ec844729-f5d4-478f-bb1b-3c3502f5f939

	measure 'Top N count' = ```
			
			VAR TopNSelected = SELECTEDVALUE('Top N Selection'[Value])
			VAR TopEduLvlTable = 
			    TOPN(
			        TopNSelected,
			        ALLSELECTED('Pseudo Customer Loyalty Table'),
			        [Total Customers]
			        )
			VAR TopEduLvlCount = 
			    CALCULATE(
			    [Total Customers],
			    KEEPFILTERS(
			        TopEduLvlTable
			        )
			    )
			VAR OthersCount = 
			    CALCULATE(
			        [Total Customers],
			        ALLSELECTED('Pseudo Customer Loyalty Table')
			    ) - 
			    CALCULATE(
			        [Total Customers],
			        TopEduLvlTable
			    )
			VAR CurrentEduLvl = SELECTEDVALUE('Pseudo Customer Loyalty Table'[Education])
			RETURN
			    IF(
			        CurrentEduLvl <> "Others",
			        TopEduLvlCount,
			        OthersCount
			    )
			```
		formatString: 0
		displayFolder: Top N & Others
		lineageTag: 79ba9989-53c4-491e-9335-f9f187cd6623

	measure Rank =
			
			IF(
			    [Top N count] <> BLANK(),
			    RANKX(
			        TOPN(
			            SELECTEDVALUE('Top N Selection'[Value]),
			            ALLSELECTED('Pseudo Customer Loyalty Table'),
			            [Total Customers]
			        ),
			        [Total Customers],,
			        DESC,
			        Dense
			    )
			)
		formatString: 0
		displayFolder: Top N & Others
		lineageTag: a903664a-8b7d-4c82-bd9b-58617778ccb6

	measure Title = ```
			
			VAR TopEduLvl = 
			    CALCULATE(
			        [Total Customers],
			        TOPN(
			            SELECTEDVALUE('Top N Selection'[Value]),
			            ALLSELECTED('Pseudo Customer Loyalty Table'[Education]),
			            [Total Customers]
			        )
			    )
			VAR TopEduLvlPct = 
			    DIVIDE(
			        TopEduLvl,
			        [Total Customers]
			    )
			RETURN
			"Top " & SELECTEDVALUE('Top N Selection'[Value]) & " Education Levels make up " & FORMAT(TopEduLvlPct,"#.#% of all customers")
			```
		displayFolder: Top N & Others
		lineageTag: 2ee26d0b-bbef-4c71-ac3d-c2b40729acf0

	measure Colour =
			
			SWITCH(
			    SELECTEDVALUE('Pseudo Customer Loyalty Table'[Education]),
			    "Others", "#D9D9D9",
			    "#031CC5")
		displayFolder: Top N & Others
		lineageTag: 337372fa-11fc-47f2-b793-b22900a3332c

	measure Test_measure1 = SUM('Customer Flight Activity'[Dollar Cost Points Redeemed])
		formatString: 0
		lineageTag: f168fd4f-8e95-40c9-9fa4-a1707147213b

	measure Test_measure2 = SUM('Customer Flight Activity'[Total Flights])
		formatString: 0
		lineageTag: 6b2ebb5e-4b87-459a-8b8f-a5a65cb84ab2

	partition 'Measure Table' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Column1"})
				in
				    #"Removed Columns"

	changedProperty = Name

	annotation PBI_ResultType = Table

